export const ProductDetails = () => {
  const products = [
    {
      name: "Aurora Desk Lamp",
      productType: "Home Decor",
      description: "A sleek LED desk lamp with adjustable brightness and a modern design.",
      imageUrl: "https://theartment.com/cdn/shop/files/aurora-lamp-556714.jpg?v=1729493625&width=1080",
      price: 49.99,
    },
    {
      name: "Everest Hiking Backpack",
      productType: "Outdoor Gear",
      description: "Durable 40L hiking backpack with multiple compartments and waterproof lining.",
      imageUrl: "https://bagazio.co.za/cdn/shop/files/BH-41-Everest-Group_1200x1200.jpg?v=1698053742",
      price: 89.99,
    },
    {
      name: "Zen Ceramic Mug",
      productType: "Kitchenware",
      description: "Handcrafted ceramic mug with a minimalist glaze finish.",
      imageUrl: "https://m.media-amazon.com/images/I/71mHvUNRyWL.jpg",
      price: 14.5,
    },
    {
      name: "Nimbus Wireless Earbuds",
      productType: "Electronics",
      description: "Noise-cancelling Bluetooth earbuds with 20 hours of battery life.",
      imageUrl: "https://computechstore.in/wp-content/uploads/2025/08/Noise-Air-Buds-Pro-6-in-Ear-Truly-Wireless-Earbuds-Nimbus-Grey-2.jpg",
      price: 79.99,
    },
    {
      name: "Cascade Water Bottle",
      productType: "Fitness",
      description: "BPA-free insulated bottle that keeps drinks cold for 24 hours.",
      imageUrl: "https://m.media-amazon.com/images/I/81z6OZ593cL.jpg",
      price: 24.99,
    },
    {
      name: "Cloud Comfort Pillow",
      productType: "Bedding",
      description: "Memory foam pillow with breathable bamboo cover.",
      imageUrl: "https://3.imimg.com/data3/FQ/HP/MY-5513435/assets-images-site-base-upload-14054349211693-cloud-package.jpg",
      price: 39.99,
    },
    {
      name: "Atlas Smartwatch",
      productType: "Wearables",
      description: "Water-resistant smartwatch with GPS, heart-rate monitor, and fitness tracking.",
      imageUrl: "https://m.media-amazon.com/images/I/61sPl8FU9NL._UF1000,1000_QL80_.jpg",
      price: 199.99,
    },
    {
      name: "Luna Yoga Mat",
      productType: "Fitness",
      description: "Eco-friendly non-slip yoga mat with 6mm cushioning.",
      imageUrl: "https://m.media-amazon.com/images/I/912mw3id-4L.jpg",
      price: 32.5,
    },
    {
      name: "Sierra Sunglasses",
      productType: "Accessories",
      description: "UV400 polarized sunglasses with lightweight frame.",
      imageUrl: "https://www.mestige.com/cdn/shop/files/MUVSG5020-BLACK_1_1445x.jpg?v=1689743351",
      price: 54.99,
    },
    {
      name: "Driftwood Wall Clock",
      productType: "Home Decor",
      description: "Rustic wooden wall clock with silent quartz movement.",
      imageUrl: "https://images.woodenstreet.de/image/cache/data/discoo-fashion/white-distress-finish-wooden-square-wall-clock/revised/updated/DF-1-810x702.jpg",
      price: 45.0,
    },
    {
      name: "Summit Running Shoes",
      productType: "Footwear",
      description: "Lightweight running shoes with breathable mesh and cushioned sole.",
      imageUrl: "https://rukminim2.flixcart.com/image/300/300/xif0q/shoe/q/c/h/-original-imahd2p4gr9zsdzs.jpeg",
      price: 110.0,
    },
    {
      name: "Auric Gold Pen",
      productType: "Stationery",
      description: "Luxury rollerball pen with gold-plated accents and smooth ink flow.",
      imageUrl: "https://i.ebayimg.com/images/g/jokAAOSw1RRnjX0c/s-l400.jpg",
      price: 29.99,
    },
    {
      name: "Pebble Bluetooth Speaker",
      productType: "Electronics",
      description: "Portable waterproof Bluetooth speaker with deep bass.",
      imageUrl: "https://m.media-amazon.com/images/I/51taGyIR-FL.jpg",
      price: 59.5,
    },
    {
      name: "Harvest Wooden Cutting Board",
      productType: "Kitchenware",
      description: "Handmade oak cutting board with juice groove and ergonomic handle.",
      imageUrl: "https://earthyblissco.com/cdn/shop/files/S69cbbc1d003a444e96e9ceaa9fb981deX_jpg_960x960q75_jpg.jpg?v=1735083359",
      price: 27.0,
    },
    {
      name: "Nova Table Lamp",
      productType: "Home Decor",
      description: "Mid-century table lamp with fabric shade and brass base.",
      imageUrl: "https://cdn.shopify.com/s/files/1/0632/2526/6422/files/1_fa8febff-18c7-4dd5-9038-2609dfb88d5b.jpg?v=1753021184",
      price: 64.99,
    },
    {
      name: "Glacier Travel Mug",
      productType: "Kitchenware",
      description: "Double-walled stainless steel mug with leak-proof lid.",
      imageUrl: "https://hypefly.co.in/_next/image?url=https%3A%2F%2Fdjm0962033frr.cloudfront.net%2FWeb_PNG_Square_The_Quencher_H2_O_Flow_State_Tumbler40oz_Glacier_Front_e82c07620a.webp&w=3840&q=75",
      price: 19.99,
    },
    {
      name: "Vortex Gaming Mouse",
      productType: "Electronics",
      description: "RGB programmable gaming mouse with adjustable DPI up to 16000.",
      imageUrl: "https://sp-ao.shortpixel.ai/client/q_glossy,ret_img,w_300/https://vortexseries.net/wp-content/uploads/2022/04/GX770-01-300x300.jpg",
      price: 49.99,
    },
    {
      name: "Boreal Hoodie",
      productType: "Clothing",
      description: "Soft fleece-lined hoodie with front pocket and adjustable hood.",
      imageUrl: "https://www.roseboreal.com/cdn/shop/files/FreeSpiritHoodie-Oak-01-LR.jpg?v=1744036118",
      price: 42.0,
    },
    {
      name: "Aria Perfume",
      productType: "Fragrance",
      description: "Elegant floral perfume with notes of jasmine and vanilla.",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ86d_HiIL78DV8y_VBlgzSu23geMTl4P33mA&s",
      price: 75.0,
    },
    {
      name: "Comet Desk Organizer",
      productType: "Office Supplies",
      description: "Multi-compartment organizer for pens, notepads, and small accessories.",
      imageUrl: "https://katib.pk/cdn/shop/files/desk.jpg?v=1738235152",
      price: 22.5,
    },
  ];
  return products;
};
